on:
  workflow_dispatch:
  push:
    tags:
      - '*'
permissions:
  contents: write
name: Release
jobs:
  goreleaser:
    name: GoReleaser
    env:
      RESTIC_VERSION: '0.17.3'
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Prepare restic binary
        run: |
          curl -sL 'https://github.com/restic/restic/releases/download/v${{ env.RESTIC_VERSION }}/restic_${{ env.RESTIC_VERSION }}_darwin_amd64.bz2' | bunzip2 >restic_amd64
          curl -sL 'https://github.com/restic/restic/releases/download/v${{ env.RESTIC_VERSION }}/restic_${{ env.RESTIC_VERSION }}_darwin_arm64.bz2' | bunzip2 >restic_arm64
          lipo -create -output restic restic_amd64 restic_arm64
          chmod +x restic
      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      - name: Build
        run: |
          make disable-code-signing VERSION=$(echo '${{ github.ref_name }}' | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+).*/\1.\2.\3/')
          make
      - name: Pack application
        run: |
          (cd Build/Products/Release && zip -9 -r 'Restic Scheduler ${{ github.ref_name }}.zip' 'Restic Scheduler.app')
          (cd Build/Products/Release && rm 'Restic Scheduler.app/Contents/XPCServices/Restic Runner.xpc/Contents/Resources/restic' && zip -9 -r 'Restic Scheduler ${{ github.ref_name }} (without restic).zip' 'Restic Scheduler.app')
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --skip=validate --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
